kind: ConfigMap
apiVersion: v1
metadata:
  name: envoy-edge
data:
  envoy.yaml: |
    static_resources:
      listeners:
      - address:
          socket_address:
            address: 0.0.0.0
            port_value: 80
        filter_chains:
        - filters:
          - name: envoy.tcp_proxy
            config:
              stat_prefix: ingress_tcp
              cluster: local_service
      clusters:
      - name: local_service
        connect_timeout: 1s
        type: strict_dns
        hosts:
        - socket_address:
            address: app-headless.default
            port_value: 3000
